# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: '.NET Core - Restore'
  inputs:
    command: 'restore'
    projects: './'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: '.NET Core - Build'
  inputs:
    command: 'build'
    arguments: '-c $(BuildConfiguration) --no-restore'
    projects: './'

- task: DotNetCoreCLI@2
  displayName: '.NET Core - Run Tests'
  inputs:
    command: 'test'
    projects: './'
