# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: '.NET Core - Restore'
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: '.NET Core - Build'
  inputs:
    command: 'build'
    arguments: '-c $(BuildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: '.NET Core - Run Tests'
  inputs:
    command: 'test'

 - task: DotNetCoreCLI@2
   displayName: 'Publish'
   inputs:
     command: 'publish'
     publishWebProjects: false
     projects: '**/DevOps-Example.csproj'
     arguments: '-c $(BuildConfiguration) -o $(Build.StagingDirectory) --no-build'
     zipAfterPublish: false
     modifyOutputPath: false
     workingDirectory: './DevOps-Example'

- task: ArchiveFiles@2
  displayName: 'Zip'
  inputs:
    rootFolderOrFile: '$(Build.StagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/devops.show.$(Build.BuildNumber).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Artifact - DevOps'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/devops.show.$(Build.BuildNumber).zip'
    ArtifactName: 'devops.show.$(Build.BuildNumber)'
    publishLocation: 'Container'